# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cbd019c64cb93b8f318d5ed8937c32cdb69f670aefcadd1219046adb200675b839bca5f9fb562d6ff7a0117befe1a7fc4bbff7152509617ae5b674c27ce24a8

test:
  secret_key_base: 11b81f2a95c3896aaba2b254fa95e55f3b064c53b3da12204733714070f66f0a48c1310464852c7ba04cc36ce4ad8e0df8f2fd4a716272e880e625922558ad8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
